/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class Frm_opciones extends javax.swing.JFrame {

    /**
     * Creates new form Frm_opciones
     */
    public Frm_opciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        verCocina = new javax.swing.JButton();
        verMenu = new javax.swing.JButton();
        pedido = new javax.swing.JButton();
        verEstadistica = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        verMesero = new javax.swing.JButton();
        verPago = new javax.swing.JButton();
        vermesas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/opciones.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verCocina.setBackground(new java.awt.Color(102, 102, 102));
        verCocina.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        verCocina.setForeground(new java.awt.Color(255, 255, 255));
        verCocina.setText("Cocina");
        verCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCocinaActionPerformed(evt);
            }
        });
        getContentPane().add(verCocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 161, 40));

        verMenu.setBackground(new java.awt.Color(102, 102, 102));
        verMenu.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        verMenu.setForeground(new java.awt.Color(255, 255, 255));
        verMenu.setText("Menú");
        verMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMenuActionPerformed(evt);
            }
        });
        getContentPane().add(verMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 153, 40));

        pedido.setBackground(new java.awt.Color(102, 102, 102));
        pedido.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        pedido.setForeground(new java.awt.Color(255, 255, 255));
        pedido.setText("Pedido");
        pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoActionPerformed(evt);
            }
        });
        getContentPane().add(pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 130, -1));

        verEstadistica.setBackground(new java.awt.Color(102, 102, 102));
        verEstadistica.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        verEstadistica.setForeground(new java.awt.Color(255, 255, 255));
        verEstadistica.setText("Estadística");
        verEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEstadisticaActionPerformed(evt);
            }
        });
        getContentPane().add(verEstadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, 40));

        Salir.setBackground(new java.awt.Color(204, 204, 204));
        Salir.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        Salir.setText("SALIR");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, -1, -1));

        verMesero.setBackground(new java.awt.Color(102, 102, 102));
        verMesero.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        verMesero.setForeground(new java.awt.Color(255, 255, 255));
        verMesero.setText("Meseros");
        verMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMeseroActionPerformed(evt);
            }
        });
        getContentPane().add(verMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 153, 40));

        verPago.setBackground(new java.awt.Color(102, 102, 102));
        verPago.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        verPago.setForeground(new java.awt.Color(255, 255, 255));
        verPago.setText("Pagos");
        verPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPagoActionPerformed(evt);
            }
        });
        getContentPane().add(verPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 134, 40));

        vermesas.setBackground(new java.awt.Color(102, 102, 102));
        vermesas.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        vermesas.setForeground(new java.awt.Color(255, 255, 255));
        vermesas.setText("Mesas");
        vermesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vermesasActionPerformed(evt);
            }
        });
        getContentPane().add(vermesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/opciones.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 703, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCocinaActionPerformed
        // TODO add your handling code here:
        Frm_cocina menu = new Frm_cocina();
        menu.setVisible(true);
    }//GEN-LAST:event_verCocinaActionPerformed

    private void verMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMenuActionPerformed
        // TODO add your handling code here:
        Frm_menu menu = new Frm_menu();
        menu.setVisible(true);

    }//GEN-LAST:event_verMenuActionPerformed

    private void pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoActionPerformed
        // TODO add your handling code here:
        Frm_pedido menu = new Frm_pedido();
        menu.setVisible(true);
    }//GEN-LAST:event_pedidoActionPerformed

    private void verEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEstadisticaActionPerformed
        // TODO add your handling code here:
        Frm_estadistica menu = new Frm_estadistica();
        menu.setVisible(true);
    }//GEN-LAST:event_verEstadisticaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void verMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMeseroActionPerformed
        // TODO add your handling code here:
        Frm_mesero menu = new Frm_mesero();
        menu.setVisible(true);
    }//GEN-LAST:event_verMeseroActionPerformed

    private void verPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPagoActionPerformed
        // TODO add your handling code here:
        Frm_pagos menu = new Frm_pagos();
        menu.setVisible(true);
    }//GEN-LAST:event_verPagoActionPerformed

    private void vermesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vermesasActionPerformed
        // TODO add your handling code here:
        Frm_mesas menu = null;
        try {
            menu = new Frm_mesas();
            menu.setVisible(true);
        } catch (SQLException ex) {
            
        }
        
    }//GEN-LAST:event_vermesasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton pedido;
    private javax.swing.JButton verCocina;
    private javax.swing.JButton verEstadistica;
    private javax.swing.JButton verMenu;
    private javax.swing.JButton verMesero;
    private javax.swing.JButton verPago;
    private javax.swing.JButton vermesas;
    // End of variables declaration//GEN-END:variables
}
