/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cb_platos = new javax.swing.JComboBox<>();
        btn_agregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_objetos = new javax.swing.JTable();
        txt_cantidad = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        btn_quitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_platos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SECO POLLO", "CALDO POLLO", "CARACHA", "ASADO POLLO", "AYAMPACO" }));
        jPanel2.add(cb_platos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, -1));

        btn_agregar.setText("OK");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, -1));

        jt_objetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DESCRIPCION", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jt_objetos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 490, 200));

        txt_cantidad.setText("1");
        txt_cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cantidadFocusLost(evt);
            }
        });
        jPanel2.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, -1));

        txt_total.setText("0.0");
        jPanel2.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 170, -1));

        txt_precio.setText("1");
        txt_precio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_precioFocusLost(evt);
            }
        });
        txt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioActionPerformed(evt);
            }
        });
        jPanel2.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, -1));

        jLabel1.setText("TOTAL");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));
        jPanel2.add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 170, 20));

        btn_quitar.setText("QUITAR");
        btn_quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_quitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        //Sección 1

        DefaultTableModel modelo = (DefaultTableModel) this.jt_objetos.getModel();
        //Sección 2

        Object[] fila = new Object[4];

        fila[0] = this.cb_platos.getSelectedItem().toString();

        fila[1] = this.txt_cantidad.getText();

        fila[2] = this.txt_precio.getText();

        fila[3] = this.txt_total.getText();
        //Sección 4
        modelo.addRow(fila);
        //Sección 5
        this.jt_objetos.setModel(modelo);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioActionPerformed
    double total_1, total_2;
    private void txt_cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cantidadFocusLost
        // TODO add your handling code here:
        total_1 = Double.parseDouble(this.txt_precio.getText()) * Double.parseDouble(this.txt_cantidad.getText());
        this.txt_total.setText(String.valueOf(total_1));
    }//GEN-LAST:event_txt_cantidadFocusLost

    private void txt_precioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_precioFocusLost
        // TODO add your handling code here:
        total_1 = Double.parseDouble(this.txt_precio.getText()) * Double.parseDouble(this.txt_cantidad.getText());
        this.txt_total.setText(String.valueOf(total_1));
    }//GEN-LAST:event_txt_precioFocusLost

    private void btn_quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarActionPerformed
        // TODO add your handling code here:
        //Sección 1
        DefaultTableModel model = (DefaultTableModel) this.jt_objetos.getModel();
        //Sección 2
        int a = this.jt_objetos.getSelectedRow();
        //Sección 3
        if (a < 0) {

            JOptionPane.showMessageDialog(null,
                    "Debe seleccionar una fila de la tabla");
        } else {
            //Sección 4
            int confirmar = JOptionPane.showConfirmDialog(null,
                    "Esta seguro que desea Eliminar el registro? ");

            //Sección 5 
            if (JOptionPane.OK_OPTION == confirmar) {

                //Sección 6
                model.removeRow(a);

                //Sección 7
                JOptionPane.showMessageDialog(null, "Registro Eliminado");

            }

        }
    }//GEN-LAST:event_btn_quitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_quitar;
    private javax.swing.JComboBox<String> cb_platos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_objetos;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
